"""Added release_date and poster_path.

Revision ID: 6446be57c154
Revises: bd67065d2e6d
Create Date: 2020-07-15 04:31:33.337459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6446be57c154'
down_revision = 'bd67065d2e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_table')
    op.drop_table('scores_table')
    op.add_column('movie_info', sa.Column('poster_path', sa.String(length=200), nullable=True))
    op.add_column('movie_info', sa.Column('release_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_info', 'release_date')
    op.drop_column('movie_info', 'poster_path')
    op.create_table('scores_table',
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tmdb_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('posiscore', sa.INTEGER(), nullable=False),
    sa.Column('negascore', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('date_created')
    )
    op.create_table('info_table',
    sa.Column('tmdb_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('movie_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('release_date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('poster_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ave_posiscore', sa.FLOAT(), nullable=True),
    sa.Column('ave_negascore', sa.FLOAT(), nullable=True),
    sa.Column('ave_combscore', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    # ### end Alembic commands ###
