"""Initial migration.

Revision ID: bd67065d2e6d
Revises: 
Create Date: 2020-07-14 23:45:00.593270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd67065d2e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_table',
    sa.Column('tmdb_id', sa.String(length=200), nullable=False),
    sa.Column('movie_name', sa.String(length=200), nullable=False),
    sa.Column('release_date', sa.String(length=10), nullable=False),
    sa.Column('poster_path', sa.String(length=200), nullable=True),
    sa.Column('ave_posiscore', sa.Float(), nullable=True),
    sa.Column('ave_negascore', sa.Float(), nullable=True),
    sa.Column('ave_combscore', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_table('scores_table',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tmdb_id', sa.String(length=200), nullable=False),
    sa.Column('posiscore', sa.Integer(), nullable=False),
    sa.Column('negascore', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date_created')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores_table')
    op.drop_table('info_table')
    # ### end Alembic commands ###
